### ISSUE TITLE
Why has this not been merged back to the parent repo?

### ISSUE THREAD

**Issue by AnmolMago** [thegranddesign/m-cli#1]
Is this an actively maintained project? It seems that the two repos have diverged. Recently discovered this tool, and it seems great (with extra features) but this fork does not have a lot of eyes on it, so unsure if I should install.

**Comment by thegranddesign** [comment]
@AnmolMago there's an open PR on the main repo to merge this in, which has been stagnant for years.  Although my fork works great, I've been looking into https://github.com/ProfileCreator/ProfileCreator as a much more scaleable solution to doing OS configs across installations.

The issue as of today is that it can't support nearly as much as what my fork supports, but I'm going to be working on moving features into it as I have time.
